# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Service.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rService.proto\"m\n\x0c\x43redenciales\x12\x13\n\x0busuarioPeer\x18\x01 \x01(\t\x12\x12\n\ncontraPeer\x18\x02 \x01(\t\x12\x12\n\nnombrePeer\x18\x03 \x01(\t\x12\x0e\n\x06puerto\x18\x04 \x01(\x05\x12\x10\n\x08hostname\x18\x05 \x01(\t\"!\n\x0c\x43onfirmacion\x12\x11\n\trespuesta\x18\x01 \x01(\t\"4\n\x0c\x41rchivosPeer\x12\x10\n\x08\x61rchivos\x18\x01 \x03(\t\x12\x12\n\nnombrePeer\x18\x02 \x01(\t\"1\n\tSolicitud\x12\x10\n\x08peticion\x18\x01 \x01(\t\x12\x12\n\nnombrePeer\x18\x02 \x01(\t\"<\n\x11SolicitudBusqueda\x12\x10\n\x08peticion\x18\x01 \x01(\t\x12\x15\n\rnombreArchivo\x18\x02 \x01(\t\">\n\x0bPeerPosesor\x12\x0c\n\x04peer\x18\x01 \x01(\t\x12\x0e\n\x06puerto\x18\x02 \x01(\x05\x12\x11\n\thost_name\x18\x03 \x01(\t2\xb4\x01\n\tPrincipal\x12\'\n\x05Login\x12\r.Credenciales\x1a\r.Confirmacion\"\x00\x12%\n\x06Logout\x12\n.Solicitud\x1a\r.Confirmacion\"\x00\x12)\n\x07Indexar\x12\r.ArchivosPeer\x1a\r.Confirmacion\"\x00\x12,\n\x06\x42uscar\x12\x12.SolicitudBusqueda\x1a\x0c.PeerPosesor\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Service_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_CREDENCIALES']._serialized_start=17
  _globals['_CREDENCIALES']._serialized_end=126
  _globals['_CONFIRMACION']._serialized_start=128
  _globals['_CONFIRMACION']._serialized_end=161
  _globals['_ARCHIVOSPEER']._serialized_start=163
  _globals['_ARCHIVOSPEER']._serialized_end=215
  _globals['_SOLICITUD']._serialized_start=217
  _globals['_SOLICITUD']._serialized_end=266
  _globals['_SOLICITUDBUSQUEDA']._serialized_start=268
  _globals['_SOLICITUDBUSQUEDA']._serialized_end=328
  _globals['_PEERPOSESOR']._serialized_start=330
  _globals['_PEERPOSESOR']._serialized_end=392
  _globals['_PRINCIPAL']._serialized_start=395
  _globals['_PRINCIPAL']._serialized_end=575
# @@protoc_insertion_point(module_scope)
