# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import Service_pb2 as Service__pb2


class PrincipalStub(object):
    """Comunicación cliente-servidorPrincipal (login(), logout(), buscar(), indexar())

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Login = channel.unary_unary(
                '/Principal/Login',
                request_serializer=Service__pb2.Credenciales.SerializeToString,
                response_deserializer=Service__pb2.Confirmacion.FromString,
                )
        self.Logout = channel.unary_unary(
                '/Principal/Logout',
                request_serializer=Service__pb2.Solicitud.SerializeToString,
                response_deserializer=Service__pb2.Confirmacion.FromString,
                )
        self.Indexar = channel.unary_unary(
                '/Principal/Indexar',
                request_serializer=Service__pb2.ArchivosPeer.SerializeToString,
                response_deserializer=Service__pb2.Confirmacion.FromString,
                )
        self.Buscar = channel.unary_unary(
                '/Principal/Buscar',
                request_serializer=Service__pb2.SolicitudBusqueda.SerializeToString,
                response_deserializer=Service__pb2.PeerPosesor.FromString,
                )


class PrincipalServicer(object):
    """Comunicación cliente-servidorPrincipal (login(), logout(), buscar(), indexar())

    """

    def Login(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Logout(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Indexar(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Buscar(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PrincipalServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Login': grpc.unary_unary_rpc_method_handler(
                    servicer.Login,
                    request_deserializer=Service__pb2.Credenciales.FromString,
                    response_serializer=Service__pb2.Confirmacion.SerializeToString,
            ),
            'Logout': grpc.unary_unary_rpc_method_handler(
                    servicer.Logout,
                    request_deserializer=Service__pb2.Solicitud.FromString,
                    response_serializer=Service__pb2.Confirmacion.SerializeToString,
            ),
            'Indexar': grpc.unary_unary_rpc_method_handler(
                    servicer.Indexar,
                    request_deserializer=Service__pb2.ArchivosPeer.FromString,
                    response_serializer=Service__pb2.Confirmacion.SerializeToString,
            ),
            'Buscar': grpc.unary_unary_rpc_method_handler(
                    servicer.Buscar,
                    request_deserializer=Service__pb2.SolicitudBusqueda.FromString,
                    response_serializer=Service__pb2.PeerPosesor.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Principal', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Principal(object):
    """Comunicación cliente-servidorPrincipal (login(), logout(), buscar(), indexar())

    """

    @staticmethod
    def Login(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Principal/Login',
            Service__pb2.Credenciales.SerializeToString,
            Service__pb2.Confirmacion.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Logout(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Principal/Logout',
            Service__pb2.Solicitud.SerializeToString,
            Service__pb2.Confirmacion.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Indexar(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Principal/Indexar',
            Service__pb2.ArchivosPeer.SerializeToString,
            Service__pb2.Confirmacion.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Buscar(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Principal/Buscar',
            Service__pb2.SolicitudBusqueda.SerializeToString,
            Service__pb2.PeerPosesor.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
